version: '3.8'

services:
    tests:
        build: .
        volumes:
            - .:/app
            - /app/node_modules
            - ./allure-results:/app/allure-results
        environment:
            - CI=true
        deploy:
            resources:
                limits:
                    memory: 4G
                    cpus: '4'
        ipc: host
        init: true
        command: ['test', '--project=chromium', '--workers=4']
