services:
    tests:
        build: .
        volumes:
            - .:/app
            - /app/node_modules
            - ./allure-results:/app/allure-results
        environment:
            - CI=true
        command: ['test', '--project=chromium']
