name: Playwright Tests
on:
    push:
        branches: [main, master, feature]
    pull_request:
        branches: [main, master]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install chromium

            - name: Run Playwright tests
              run: npx playwright test --project=chromium
              env:
                  CI: true

            - name: Generate Allure report
              run: |
                  npx allure generate allure-results --clean -o allure-report
            - name: Upload Allure report
              uses: actions/upload-artifact@v3
              with:
                  name: allure-report
                  path: allure-report

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./allure-report
