name: Playwright Tests
on:
    push:
        branches: [main, master, feature/**]
    pull_request:
        branches: [main, master, feature/**]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and run tests
              run: |
                  docker build -t playwright-tests .
                  docker run --rm -v $(pwd)/allure-results:/app/allure-results playwright-tests

            - name: Clean Allure report directory
              run: rm -rf allure-report

            - name: Generate Allure report
              run: npx allure generate allure-results -o allure-report

            - name: Upload Allure report
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: allure-report
                  path: allure-report

            - name: Deploy to GitHub Pages
              id: deployment
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.MY_TOKEN }}
                  publish_dir: ./allure-report
                  destination_dir: .
                  commit_message: 'Deploy Allure report to root'
